on:
  pull_request:
    types: [opened, closed]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "text": "새로운 PR이 생성되었습니다.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.event.pull_request.title }}* - ${{ github.event.pull_request.user.login }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "(https://github.com/minje-cho/webhook-test/pull/${{ github.event.pull_request.number }})[바로가기]"
                }
              }
            ]
          }

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
