name: Slack Notification

on:
  pull_request:
    types: [opened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: action-slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        status: ${{ job.status }}
        author_name: ${{ github.event.pull_request.user.login }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
