on:
  pull_request:
    types: [opened, closed]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "text": "새로운 PR이 생성되었습니다.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "새로운 PR이 생성되었습니다:\n*<https://github.com/minje-cho/webhook-test/pull/${{ github.event.pull_request.number }}|PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}>*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*제목:*\n${{ github.event.pull_request.title }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*작성자:*\n${{ github.event.pull_request.user.login }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*내용:*\n${{ github.event.pull_request.user.body }}"
                  }
                ]
              }
            ]
          }

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
