name: Slack Notification

on:
  pull_request:
    types: [opened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: action-slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "key": "value",
            "foo": "bar"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
