on:
  pull_request:
    types: [opened, closed]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
          	"blocks": [
          		{
          			"type": "section",
          			"text": {
          				"type": "mrkdwn",
          				"text": "*<https://github.com/minje-cho/webhook-test/pull/${{ github.event.pull_request.number }}|PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}>*"
          			}
          		},
          		{
          			"type": "section",
             			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*작성자:*\n${{ github.actor }}"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*브랜치:*\n${{ github.head_ref }}"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*리뷰어:*\n${{ github.reviewer }}"
            				}
            			]
          		}
          	]
          }

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
