name: Notify Slack on PR

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "key": "value",
            "foo": "bar"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
